package types_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/NamhaeSusan/go-arch-guard/analyzer"
	"github.com/NamhaeSusan/go-arch-guard/core"
	"github.com/NamhaeSusan/go-arch-guard/presets"
	types "github.com/NamhaeSusan/go-arch-guard/rules/types"
)

const noPanicRule = "errors.no-panic-in-domain"

func TestNoPanicInDomainSpec(t *testing.T) {
	spec := types.NewNoPanicInDomain(types.WithSeverity(core.Error)).Spec()

	if spec.ID != noPanicRule {
		t.Fatalf("ID = %q, want %s", spec.ID, noPanicRule)
	}
	if spec.DefaultSeverity != core.Error {
		t.Fatalf("DefaultSeverity = %v, want Error", spec.DefaultSeverity)
	}
	got := spec.ViolationIDs()
	if len(got) != 1 || got[0] != noPanicRule {
		t.Fatalf("ViolationIDs() = %v, want [%s]", got, noPanicRule)
	}
}

func TestNoPanicInDomainFlagsDomainAndAppFailures(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/payment/core/model/payment.go": `package model

type Payment struct{ Status string }

func Authorized(payment Payment) Payment {
	if payment.Status != "pending" {
		panic("invalid state: must be pending")
	}
	payment.Status = "authorized"
	return payment
}
`,
		"internal/domain/payment/app/service.go": `package app

import (
	"log"
	"os"
)

func Place() {
	log.Fatal("cannot place order")
	log.Fatalf("cannot place %s", "order")
	log.Fatalln("cannot place order")
	os.Exit(1)
}
`,
		"internal/domain/payment/handler/http/handler.go": `package http

func Handle() {
	panic("transport panic is outside default inspected layers")
}
`,
	})

	got := types.NewNoPanicInDomain().Check(ctx)

	for _, want := range []string{"panic", "log.Fatal", "log.Fatalf", "log.Fatalln", "os.Exit"} {
		assertNoPanicViolation(t, got, want)
	}
	assertViolationCount(t, got, noPanicRule, 5)
}

func TestNoPanicInDomainAllowsErrorReturns(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

import stderrors "errors"

type Order struct{ ID string }

var ErrEmptyOrderID = stderrors.New("empty order id")

func NewOrder(id string) (Order, error) {
	if id == "" {
		return Order{}, ErrEmptyOrderID
	}
	return Order{ID: id}, nil
}
`,
	})

	got := types.NewNoPanicInDomain().Check(ctx)
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainIgnoresShadowedPanicFunction(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

func panic(msg string) string {
	return msg
}

func NewOrder() string {
	return panic("local helper, not builtin panic")
}
`,
	})

	got := types.NewNoPanicInDomain().Check(ctx)
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainSkipsBodylessFunctionDeclarations(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/order/core/model/external.go": `package model

func external()
`,
	})

	got := core.Run(ctx, core.NewRuleSet(types.NewNoPanicInDomain()))
	assertNoRule(t, got, "meta.rule-panic")
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainRequiresConfiguredInternalRootPrefix(t *testing.T) {
	ctx := panicContextWithPatterns(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

type Order struct{}
`,
		"tools/internal/domain/order/core/model/order.go": `package model

func NewOrder() {
	panic("tool helper package, not project internal root")
}
`,
	}, nil, "...")

	got := types.NewNoPanicInDomain().Check(ctx)
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainInspectedLayersAreConfigurable(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/payment/handler/http/handler.go": `package http

func Handle() {
	panic("handler is not checked by default")
}
`,
	})

	got := types.NewNoPanicInDomain().Check(ctx)
	assertNoRule(t, got, noPanicRule)

	got = types.NewNoPanicInDomain(
		types.WithInspectedLayers("handler"),
	).Check(ctx)
	assertNoPanicViolation(t, got, "panic")
}

func TestNoPanicInDomainSkipsTestsGeneratedAndExcludedFiles(t *testing.T) {
	ctx := panicContextWithExclude(t, map[string]string{
		"internal/domain/payment/core/model/payment_test.go": `package model

func TestPanic() { panic("test panic") }
`,
		"internal/domain/payment/core/model/generated.go": `// Code generated by test. DO NOT EDIT.
package model

func Generated() { panic("generated panic") }
`,
		"internal/domain/payment/core/model/excluded.go": `package model

func Excluded() { panic("excluded panic") }
`,
	}, []string{"internal/domain/payment/core/model/excluded.go"})

	got := types.NewNoPanicInDomain().Check(ctx)
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainAllowlistsPathsAndFunctions(t *testing.T) {
	ctx := panicContext(t, map[string]string{
		"internal/domain/payment/core/model/must.go": `package model

func MustPayment() {
	panic("allowed helper")
}
`,
		"internal/domain/payment/core/model/build.go": `package model

func BuildPayment() {
	panic("not allowed")
}
`,
	})

	got := types.NewNoPanicInDomain(
		types.WithAllowedPaths("internal/domain/payment/core/model/must.go"),
	).Check(ctx)
	assertViolationCount(t, got, noPanicRule, 1)
	assertNoPanicViolation(t, got, "panic")

	got = types.NewNoPanicInDomain(
		types.WithAllowedFunctions("Must*"),
	).Check(ctx)
	assertViolationCount(t, got, noPanicRule, 1)
	assertNoPanicViolation(t, got, "panic")
}

func TestNoPanicInDomainModuleMismatchEmitsMetaWarning(t *testing.T) {
	root := t.TempDir()
	writePanicFile(t, filepath.Join(root, "go.mod"), "module example.com/shop\n\ngo 1.26.1\n")
	writePanicFile(t, filepath.Join(root, "internal/domain/payment/core/model/payment.go"), `package model

func Pay() { panic("bad") }
`)
	pkgs, err := analyzer.Load(root, "internal/...")
	if err != nil {
		t.Fatal(err)
	}
	ctx := core.NewContext(pkgs, "example.com/other", root, presets.DDD(), nil)

	got := types.NewNoPanicInDomain().Check(ctx)

	assertViolationCount(t, got, "meta.no-matching-packages", 1)
	assertNoRule(t, got, noPanicRule)
}

func TestNoPanicInDomainIsInRecommendedDDD(t *testing.T) {
	for _, rule := range presets.RecommendedDDD().Rules() {
		spec := rule.Spec()
		if spec.ID == noPanicRule {
			if spec.DefaultSeverity != core.Error {
				t.Fatalf("DefaultSeverity = %v, want Error", spec.DefaultSeverity)
			}
			return
		}
	}
	t.Fatalf("%s missing from RecommendedDDD()", noPanicRule)
}

func panicContext(t *testing.T, files map[string]string) *core.Context {
	t.Helper()
	return panicContextWithExclude(t, files, nil)
}

func panicContextWithExclude(t *testing.T, files map[string]string, exclude []string) *core.Context {
	t.Helper()
	return panicContextWithPatterns(t, files, exclude, "internal/...")
}

func panicContextWithPatterns(t *testing.T, files map[string]string, exclude []string, patterns ...string) *core.Context {
	t.Helper()

	root := t.TempDir()
	writePanicFile(t, filepath.Join(root, "go.mod"), "module example.com/shop\n\ngo 1.26.1\n")
	for name, content := range files {
		writePanicFile(t, filepath.Join(root, name), content)
	}
	pkgs, err := analyzer.Load(root, patterns...)
	if err != nil {
		t.Fatal(err)
	}
	return core.NewContext(pkgs, "example.com/shop", root, presets.DDD(), exclude)
}

func writePanicFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func assertNoPanicViolation(t *testing.T, violations []core.Violation, want string) {
	t.Helper()
	for _, v := range violations {
		if v.Rule == noPanicRule && strings.Contains(v.Message, want) {
			if v.DefaultSeverity != core.Warning || v.EffectiveSeverity != core.Warning {
				t.Fatalf("severity = default %v effective %v, want Warning/Warning", v.DefaultSeverity, v.EffectiveSeverity)
			}
			return
		}
	}
	t.Fatalf("expected %s violation containing %q, got %+v", noPanicRule, want, violations)
}

func assertViolationCount(t *testing.T, violations []core.Violation, rule string, want int) {
	t.Helper()
	var got int
	for _, v := range violations {
		if v.Rule == rule {
			got++
		}
	}
	if got != want {
		t.Fatalf("%s violation count = %d, want %d; got %+v", rule, got, want, violations)
	}
}

func assertNoRule(t *testing.T, violations []core.Violation, rule string) {
	t.Helper()
	for _, v := range violations {
		if v.Rule == rule {
			t.Fatalf("unexpected %s violation: %+v", rule, v)
		}
	}
}
