package dependency_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/NamhaeSusan/go-arch-guard/analyzer"
	"github.com/NamhaeSusan/go-arch-guard/core"
	"github.com/NamhaeSusan/go-arch-guard/presets"
	"github.com/NamhaeSusan/go-arch-guard/rules/dependency"
)

func TestNoSideEffectCallInCoreSpec(t *testing.T) {
	spec := dependency.NewNoSideEffectCallInCore(dependency.WithSeverity(core.Error)).Spec()

	if spec.ID != "purity.no-side-effect-call-in-core" {
		t.Fatalf("ID = %q, want purity.no-side-effect-call-in-core", spec.ID)
	}
	if spec.DefaultSeverity != core.Error {
		t.Fatalf("DefaultSeverity = %v, want Error", spec.DefaultSeverity)
	}
	got := spec.ViolationIDs()
	if len(got) != 1 || got[0] != "purity.no-side-effect-call-in-core" {
		t.Fatalf("ViolationIDs() = %v, want [purity.no-side-effect-call-in-core]", got)
	}
}

func TestNoSideEffectCallInCoreFlagsDefaultDeniedCalls(t *testing.T) {
	ctx := purityContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

import (
	"crypto/rand"
	"log"
	mathrand "math/rand"
	"net/http"
	"os"
	"time"
)

type Order struct {
	ID        string
	CreatedAt time.Time
}

func NewOrder(id string) Order {
		log.Println("creating order")
		_ = os.Getenv("SHOP_CURRENCY")
		_, _ = os.ReadFile("seed")
		_ = os.WriteFile("seed", nil, 0o644)
		_, _ = os.Create("seed")
		_ = os.Remove("seed")
		_, _ = http.Get("https://example.com")
		_, _ = http.DefaultClient.Get("https://example.com")
		_ = mathrand.Int()
		_, _ = rand.Read(nil)
		return Order{ID: id, CreatedAt: time.Now()}
	}
	`,
	})

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)

	for _, want := range []string{
		"log.Println",
		"os.ReadFile",
		"os.WriteFile",
		"os.Create",
		"os.Remove",
		"net/http.Get",
		"net/http.(*Client).Get",
		"math/rand.Int",
		"crypto/rand.Read",
		"time.Now",
	} {
		assertPurityViolation(t, got, want)
	}
	assertPurityViolation(t, got, "os.Getenv")
}

func TestNoSideEffectCallInCoreAllowsTypeOnlyImportsAndInjectedValues(t *testing.T) {
	ctx := purityContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

import "time"

type Order struct {
	ID        string
	CreatedAt time.Time
}

func NewOrder(id string, now time.Time) Order {
	return Order{ID: id, CreatedAt: now}
}
`,
	})

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)
	if len(got) != 0 {
		t.Fatalf("type-only imports and injected values should pass, got %+v", got)
	}
}

func TestNoSideEffectCallInCoreDeniedAndAllowedCallsAreConfigurable(t *testing.T) {
	ctx := purityContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

import "time"

type Order struct{ CreatedAt time.Time }

func NewOrder(now time.Time) Order {
	return Order{CreatedAt: time.Now()}
}
`,
	})

	got := dependency.NewNoSideEffectCallInCore(
		dependency.WithAllowedCalls("time.Now"),
	).Check(ctx)
	if len(got) != 0 {
		t.Fatalf("allowed time.Now should pass, got %+v", got)
	}

	got = dependency.NewNoSideEffectCallInCore(
		dependency.WithDeniedCalls("time.Time"),
	).Check(ctx)
	if len(got) != 0 {
		t.Fatalf("non-call time.Time type should not be flagged, got %+v", got)
	}
}

func TestNoSideEffectCallInCoreInspectedLayersAreConfigurable(t *testing.T) {
	ctx := purityContext(t, map[string]string{
		"internal/domain/order/app/service.go": `package app

import "time"

func Now() time.Time { return time.Now() }
`,
	})

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)
	if len(got) != 0 {
		t.Fatalf("app layer should not be checked by default, got %+v", got)
	}

	got = dependency.NewNoSideEffectCallInCore(
		dependency.WithInspectedLayers("app"),
	).Check(ctx)
	assertPurityViolation(t, got, "time.Now")
}

func TestNoSideEffectCallInCoreModuleMismatchEmitsMetaWarning(t *testing.T) {
	root := t.TempDir()
	writePurityFile(t, filepath.Join(root, "go.mod"), "module example.com/shop\n\ngo 1.25.0\n")
	writePurityFile(t, filepath.Join(root, "internal/domain/order/core/model/order.go"), `package model

import "time"

func Now() time.Time { return time.Now() }
`)
	pkgs, err := analyzer.Load(root, "internal/...")
	if err != nil {
		t.Fatal(err)
	}
	ctx := core.NewContext(pkgs, "example.com/other", root, presets.DDD(), nil)

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)

	assertViolationCount(t, got, "meta.no-matching-packages", 1)
	assertNoPurityViolation(t, got)
}

func TestNoSideEffectCallInCoreSkipsTestsGeneratedAndExcludedFiles(t *testing.T) {
	ctx := purityContextWithExclude(t, map[string]string{
		"internal/domain/order/core/model/order_test.go": `package model

import "time"

func TestNow() { _ = time.Now() }
`,
		"internal/domain/order/core/model/generated.go": `// Code generated by test. DO NOT EDIT.
package model

import "time"

func GeneratedNow() time.Time { return time.Now() }
`,
		"internal/domain/order/core/model/excluded.go": `package model

import "time"

func ExcludedNow() time.Time { return time.Now() }
`,
	}, []string{"internal/domain/order/core/model/excluded.go"})

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)
	if len(got) != 0 {
		t.Fatalf("tests, generated files, and excluded files should pass, got %+v", got)
	}
}

func TestNoSideEffectCallInCoreDoesNotTreatOrdinaryCommentsAsGenerated(t *testing.T) {
	ctx := purityContext(t, map[string]string{
		"internal/domain/order/core/model/order.go": `package model

import "time"

func Now() time.Time {
	// Code generated by a misleading inline comment. DO NOT EDIT.
	return time.Now()
}
`,
	})

	got := dependency.NewNoSideEffectCallInCore().Check(ctx)
	assertPurityViolation(t, got, "time.Now")
}

func TestNoSideEffectCallInCoreIsOptInForRecommendedDDD(t *testing.T) {
	for _, rule := range presets.RecommendedDDD().Rules() {
		if rule.Spec().ID == "purity.no-side-effect-call-in-core" {
			t.Fatalf("purity.no-side-effect-call-in-core must stay opt-in, found in RecommendedDDD()")
		}
	}
}

func purityContext(t *testing.T, files map[string]string) *core.Context {
	t.Helper()
	return purityContextWithExclude(t, files, nil)
}

func purityContextWithExclude(t *testing.T, files map[string]string, exclude []string) *core.Context {
	t.Helper()
	root := t.TempDir()
	writePurityFile(t, filepath.Join(root, "go.mod"), "module example.com/shop\n\ngo 1.25.0\n")
	for name, content := range files {
		writePurityFile(t, filepath.Join(root, name), content)
	}
	pkgs, err := analyzer.Load(root, "internal/...")
	if err != nil {
		t.Fatal(err)
	}
	return core.NewContext(pkgs, "example.com/shop", root, presets.DDD(), exclude)
}

func writePurityFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func assertPurityViolation(t *testing.T, violations []core.Violation, want string) {
	t.Helper()
	for _, v := range violations {
		if v.Rule == "purity.no-side-effect-call-in-core" && strings.Contains(v.Message, want) {
			if v.DefaultSeverity != core.Warning || v.EffectiveSeverity != core.Warning {
				t.Fatalf("severity = default %v effective %v, want Warning/Warning", v.DefaultSeverity, v.EffectiveSeverity)
			}
			return
		}
	}
	t.Fatalf("expected purity.no-side-effect-call-in-core violation containing %q, got %+v", want, violations)
}

func assertNoPurityViolation(t *testing.T, violations []core.Violation) {
	t.Helper()
	for _, v := range violations {
		if v.Rule == "purity.no-side-effect-call-in-core" {
			t.Fatalf("unexpected purity violation: %+v", v)
		}
	}
}

func assertViolationCount(t *testing.T, violations []core.Violation, rule string, want int) {
	t.Helper()
	var got int
	for _, v := range violations {
		if v.Rule == rule {
			got++
		}
	}
	if got != want {
		t.Fatalf("%s violation count = %d, want %d; got %+v", rule, got, want, violations)
	}
}
