package testpolicy_test

import (
	"github.com/NamhaeSusan/go-arch-guard/core"
	"github.com/NamhaeSusan/go-arch-guard/rules/testpolicy"
	"testing"
)

func TestStrictMocks(t *testing.T) {
	for _, tc := range []struct {
		name, source string
		want         int
	}{
		{"renamed", "package p; type transport struct{}; func (transport) Call() {}", 1},
		{"function", "package p; type transport func(); func (transport) Call() {}", 1},
		{"data", "package p; type response struct { Code int }", 0},
		{"mockery", "// Code generated by mockery; DO NOT EDIT.\npackage p; type Mock struct{}; func (Mock) Call() {}", 0},
		{"other-generator", "// Code generated by something; DO NOT EDIT.\npackage p; type Mock struct{}; func (Mock) Call() {}", 1},
		{"malformed", "package p; func (", 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ctx := auditContext(t, map[string]string{"p/a.go": "package p", "only_tests/double_test.go": tc.source}, core.Architecture{})
			got := testpolicy.NewNoHandMock(testpolicy.WithStrictMocks()).Check(ctx)
			if len(got) != tc.want {
				t.Fatalf("got %v, want %d", got, tc.want)
			}
		})
	}
}
func TestStrictMockAllowlistAndExclusions(t *testing.T) {
	ctx := auditContext(t, map[string]string{
		"p/a.go":            "package p",
		"p/helper_test.go":  "package p; type helper struct{}; func (helper) Check(){}",
		"p/ignored_test.go": "package p; type ignored struct{};func (ignored) Call(){}",
		"p/double_test.go":  "package p; type other struct{};func (other) Call(){}",
	}, core.Architecture{}, "p/ignored_test.go")
	got := testpolicy.NewNoHandMock(testpolicy.WithStrictMocks(), testpolicy.WithAllowedTestReceivers("p/helper_test.go:helper")).Check(ctx)
	if len(got) != 1 || got[0].File != "p/double_test.go" {
		t.Fatalf("got %v", got)
	}
}
