package testpolicy

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/NamhaeSusan/go-arch-guard/core"
	"github.com/NamhaeSusan/go-arch-guard/core/analysisutil"
)

func isMockeryGenerated(file *ast.File) bool {
	if !ast.IsGenerated(file) {
		return false
	}
	for _, group := range file.Comments {
		if group.Pos() > file.Package {
			break
		}
		for _, comment := range group.List {
			if comment.Text == "// Code generated by mockery; DO NOT EDIT." {
				return true
			}
		}
	}
	return false
}

// Scan the module tree, including test-only packages. Nested modules and
// testdata are separate analysis scopes. Generated provenance must additionally
// be checked by regenerating mocks in CI; comments alone are not authentication.
func (r *NoHandMock) checkStrict(ctx *core.Context) []core.Violation {
	var out []core.Violation
	add := func(path string, line int, message string) {
		out = append(out, core.Violation{File: path, Line: line, Rule: r.Spec().ID,
			Message: message, Fix: "generate interface mocks with mockery; check regeneration in CI",
			DefaultSeverity: r.severity, EffectiveSeverity: r.severity})
	}
	root := ctx.Root()
	if root == "" {
		add("", 0, "cannot inspect test mocks: module root is missing")
		return out
	}
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if walkErr != nil {
			add(rel, 0, fmt.Sprintf("cannot inspect test mocks: %v", walkErr))
			return nil
		}
		if entry.IsDir() {
			if path != root {
				if strings.HasPrefix(entry.Name(), ".") || entry.Name() == "vendor" || entry.Name() == "testdata" {
					return filepath.SkipDir
				}
				if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if !strings.HasSuffix(path, "_test.go") || ctx.IsExcluded(rel) {
			return nil
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			add(rel, 0, fmt.Sprintf("cannot parse test mocks: %v", err))
			return nil
		}
		if isMockeryGenerated(file) {
			return nil
		}
		seen := map[string]bool{}
		analysisutil.WalkFuncDecls(file, func(fd *ast.FuncDecl) {
			if fd.Recv == nil || len(fd.Recv.List) == 0 {
				return
			}
			receiver := analysisutil.ReceiverTypeName(fd.Recv.List[0].Type)
			if seen[receiver] || slices.Contains(r.allowed, rel+":"+receiver) {
				return
			}
			seen[receiver] = true
			add(rel, fset.Position(fd.Pos()).Line, fmt.Sprintf("handwritten test receiver %q is forbidden; use a mockery-generated interface mock", receiver))
		})
		return nil
	})
	if err != nil {
		add("", 0, fmt.Sprintf("cannot inspect test mocks: %v", err))
	}
	return out
}
